name: "Deploy to Production"
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the code"
        uses: actions/checkout@v2
      - name: "Install dependencies and build"
        run: |
          npm install
          npm run build
      - name: "Deploy to production"
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd /var/www/example.com
            rm -rf *
            cp -r /path/to/your/app/* .
          host: your-server.com
          username: your-ssh-username
          port: 22